services:
  chat:
    image: kiritoxjf/vv-chat:0.1
    restart: always
    container_name: chat
    environment:
      - TZ=Asia/Shanghai
    networks:
      chat_network:
    ports:
      - "80:80"
    volumes:
      - /home/chat/logs:/var/log
networks:
  chat_network: